# ---------------------
# Common
# ---------------------

x-common: &common
  volumes: !override []



# ---------------------
# Services
# ---------------------

services:

  base:
    command: ":"
    build:
      target: "production"

  backend:
    <<: *common
    command: ["pnpm backend serve"]

  frontend:
    <<: *common
    command: ["pnpm frontend build && PORT=${FRONTEND_PORT} node ./packages/frontend/dist/server/entry.mjs"]