# ---------------------
# Volumes
# ---------------------

volumes:
  pnpm_store:



# ---------------------
# Common
# ---------------------

x-common: &common
  image: "pnpm-docker"
  pull_policy: never
  volumes:
    - pnpm_store:${PNPM_DIR}
    - ./:${WORK_DIR}
  env_file:
    - .env
  depends_on:
    - base



# ---------------------
# Services
# ---------------------

services:

  base:
    image: "pnpm-docker"
    command: "sleep infinity"
    build:
      context: .
      target: "base"
      args:
        WORK_DIR: ${WORK_DIR}
        PNPM_DIR: ${PNPM_DIR}

  backend:
    <<: *common
    command: ["pnpm backend install && pnpm backend serve"]
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    <<: *common
    command: ["pnpm frontend install && pnpm frontend serve"]
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"