# ---------------------
# Common
# ---------------------

x-common: &common
  volumes: !override
    - pnpm_store:${PNPM_DIR}



# ---------------------
# Services
# ---------------------

services:

  backend:
    <<: *common
    build:
      target: "production"
      args:
        PACKAGE: "backend"
    command: ["node server"]

  frontend:
    <<: *common
    build:
      target: "production"
      args:
        PACKAGE: "frontend"
    command: ["PORT=${FRONTEND_PORT} node ./dist/server/entry.mjs"]