# ---------------------
# Common
# ---------------------

x-common: &common
  build:
    target: "production"
  volumes: !override []



# ---------------------
# Services
# ---------------------

services:

  backend:
    <<: *common
    command: ["pnpm backend serve"]

  frontend:
    <<: *common
    command: ["pnpm frontend build && PORT=${FRONTEND_PORT} node ./packages/frontend/dist/server/entry.mjs"]